import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

function TopNav() {
  return (
    <nav className="flex w-full items-center justify-between border-b p-4 text-xl font-semibold">
      <div className=""> Gallery </div>

      <div> Sign In </div>
    </nav>
  );
}
function BottomNav() {
  return (
    <nav className="bg-gray-800 p-4">
      <div className="container mx-auto">
        <h1 className="text-white text-lg">Bottom Navigation</h1>
      </div>
    </nav>
  );
}
function SideNav() {
  return (
    <nav className="bg-gray-800 p-4">
      <div className="container mx-auto">
        <h1 className="text-white text-lg">Side Navigation</h1>
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TopNav />
        {children}
      </body>
    </html>
  );
}
